# =====================
# Globals (multipliers)
# =====================
globals:
  - id: flow1_multiplier
    type: float
    restore_value: true
    initial_value: '0.00172'

  - id: flow1_total_multiplier
    type: float
    restore_value: true
    initial_value: '0.00163'

  - id: flow2_multiplier
    type: float
    restore_value: true
    initial_value: '0.00172'

  - id: flow2_total_multiplier
    type: float
    restore_value: true
    initial_value: '0.00163'

# =====================
# Substitutions
# =====================
substitutions:
  device_name: waterflowkit
  friendly_name: WaterFlowKit
  waterflowkit_software_version: "2025.11"

# =====================
# ESPHome core
# =====================
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "smarthomeshop.waterflowkit"
    version: ${waterflowkit_software_version}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://DBMcoder/waterflowkit/waterflowkit.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: ${device_name}

captive_portal:

web_server:
  port: 80

# =====================
# Switch
# =====================
switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"

# =====================
# LEDs
# =====================
output:
  - platform: ledc
    pin: GPIO16
    id: output_led_green
  - platform: ledc
    pin: GPIO17
    id: output_led_red
  - platform: ledc
    pin: GPIO04
    id: output_led_blue

light:
  - platform: monochromatic
    id: light_led_green
    output: output_led_green
  - platform: status_led
    id: light_led_red
    output: output_led_red
  - platform: monochromatic
    id: light_led_blue
    output: output_led_blue

# =====================
# I2C
# =====================
i2c:
  sda: GPIO21
  scl: GPIO22

# =====================
# Time
# =====================
time:
  - platform: homeassistant
    id: time_homeassistant
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - platform: sntp
    id: time_sntp

# =====================
# Sensors
# =====================
sensor:
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s

  - platform: uptime
    id: sensor_uptime

  - platform: template
    id: sensor_uptime_timestamp
    name: "${friendly_name} Uptime"
    device_class: timestamp
    update_interval: never
    lambda: |-
      return id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state;

  - platform: hdc1080
    temperature:
      id: sensor_temperature
      name: "Temperature"
      filters:
        - offset: -4.5
    humidity:
      id: sensor_humidity
      name: "Humidity"
      filters:
        - offset: 12
    update_interval: 60s

  # -------- Flow 1 temperature --------
  - platform: adc
    id: source_sensor
    pin: GPIO36
    attenuation: 11db
    internal: true

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    resistor: 50kOhm
    internal: true

  - platform: ntc
    id: flow1_water_temperature
    sensor: resistance_sensor
    name: "Flow1 Water Temperature"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 50kOhm

  # -------- Flow 2 temperature --------
  - platform: adc
    id: source_sensor2
    pin: GPIO39
    attenuation: 11db
    internal: true

  - platform: resistance
    id: resistance_sensor2
    sensor: source_sensor2
    resistor: 50kOhm
    internal: true

  - platform: ntc
    id: flow2_water_temperature
    sensor: resistance_sensor2
    name: "Flow2 Water Temperature"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 50kOhm

  # -------- Flow sensor 1 --------
  - platform: pulse_counter
    id: water_usage
    name: "Flow1 Current water usage"
    pin:
      number: GPIO26
      mode:
        input: true
        pullup: true
    unit_of_measurement: "L/min"
    update_interval: 5s
    filters:
      - lambda: |-
          return x * id(flow1_multiplier);
    total:
      id: sensor_pulse_meter_total
      name: "Flow1 Total Consumption"
      unit_of_measurement: "L"
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 3
      filters:
        - lambda: |-
            return x * id(flow1_total_multiplier);

  # -------- Flow sensor 2 --------
  - platform: pulse_counter
    id: sens2_water_usage
    name: "Flow2 Current water usage"
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    unit_of_measurement: "L/min"
    update_interval: 5s
    filters:
      - lambda: |-
          return x * id(flow2_multiplier);
    total:
      id: sens_2_sensor_pulse_meter_total
      name: "Flow2 Total Consumption"
      unit_of_measurement: "L"
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 3
      filters:
        - lambda: |-
            return x * id(flow2_total_multiplier);

# =====================
# Text sensors
# =====================
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP address"
    ssid:
      name: "${friendly_name} Connected SSID"

  - platform: version
    name: "${friendly_name} ESPHome Version"

  - platform: template
    name: "${friendly_name} Software Version"
    lambda: |-
      return {"${waterflowkit_software_version}"};

# =====================
# Number inputs (HA)
# =====================
number:
  - platform: template
    name: "Flow1 multiplier"
    optimistic: true
    restore_value: true
    min_value: 0.0001
    max_value: 1
    step: 0.000001
    initial_value: 0.00172
    set_action:
      - lambda: |-
          id(flow1_multiplier) = x;

  - platform: template
    name: "Flow1 total multiplier"
    optimistic: true
    restore_value: true
    min_value: 0.0001
    max_value: 1
    step: 0.000001
    initial_value: 0.00163
    set_action:
      - lambda: |-
          id(flow1_total_multiplier) = x;

  - platform: template
    name: "Flow2 multiplier"
    optimistic: true
    restore_value: true
    min_value: 0.0001
    max_value: 1
    step: 0.000001
    initial_value: 0.00172
    set_action:
      - lambda: |-
          id(flow2_multiplier) = x;

  - platform: template
    name: "Flow2 total multiplier"
    optimistic: true
    restore_value: true
    min_value: 0.0001
    max_value: 1
    step: 0.000001
    initial_value: 0.00163
    set_action:
      - lambda: |-
          id(flow2_total_multiplier) = x;
